### ISSUE TITLE
Adevertise host

### ISSUE THREAD

**Issue by ch3lo** [twosigma/satellite#55]
Hi,

I recently deployed 3 mesos/master (master<1|2|3>) and 2 mesos/slave (slave<1|2>) each one with satellite/master and satellite/slave respectively. Each server has 2 interfaces for internal (10.10.10.X) and external traffic (x.x.x.x).

I'm using this config in master:

satellite:
```
(ns satellite.core)
(def settings
  (merge settings
         {:mesos-master-url (url/url "http://master3.internal.domain.com:5050")
          :sleep-time 5000
          :zookeeper "10.10.10.1:2181,10.10.10.2:2181,10.10.10.3:2181"
          :local-whitelist-path "/etc/mesos/whitelist"
          :riemann-config "./config/riemann-debug.clj"
          :riemann-tcp-server-options {:host "0.0.0.0" }
          :service-host "0.0.0.0"}))
```

riemann:
```
(streams prn)
```

Here is my satellite/slave config:

```
(def mesos-work-dir "/tmp/mesos")

(def settings
  {:satellites [{:host "master1.internal.domain.com"}
                {:host "master2.internal.domain.com"}
                {:host "master3.internal.domain.com"}]
   :service "mesos/slave/"
   :comets [(satellite-slave.recipes/free-memory 50 (-> 60 t/seconds))
            (satellite-slave.recipes/free-swap   50 (-> 60 t/seconds))
            (satellite-slave.recipes/percentage-used 90 "/tmp" (-> 60 t/seconds))
            (satellite-slave.recipes/percentage-used 90 "/var" (-> 60 t/seconds))
            (satellite-slave.recipes/percentage-used 90 mesos-work-dir
                                                     (-> 60 t/seconds))
            (satellite-slave.recipes/num-uninterruptable-processes 10 (-> 60 t/seconds))
            (satellite-slave.recipes/load-average 30 (-> 60 t/seconds))

            {:command ["echo" "17"]
             :schedule (every (-> 60 t/seconds))
             :output (fn [{:keys [out err exit]}]
                       (let [v (-> out
                                   (clojure.string/split #"\s+")
                                   first
                                   (Integer/parseInt))]
                         [{:state "ok"
                           :metric v
                           :ttl 300
                           :description "example test -- number of files/dirs in cwd"}]))}]})
``` 

I can see metrics output in my slaves and satellite/leader. When I restart mesos the satellite/leader linked with mesos/leader changes his verbosity and I can see more logs in the new satellite/leader. I can think it's the desired behavior.

In zookeeper I can see my whitelist with 2 entries (my 2 slaves), but they are registered with my external domain.

I configured the internal interface but in satellite/leader I see logs with external.domain.com and internal.domain.com. Why I have this behavior? How can I force his hostname.

Regards

**Comment by mforsyth** [comment]
Hi @ch3lo ,

Thanks for contacting us! 

The behavior of the Riemann java client (and therefore the Clojure client that uses it) is to set the host to the result of java.net.InetAddress.getLocalHost().getHostName(), if there is no host attribute that was manually associated with the event.   

So one way to get to where you need to go is to configure your systems such that  java.net.InetAddress.getLocalHost().getHostName() will return the internal domain name. 

If that's not an option, the other way to go would be to have satellite-slave associate a :host attribute with each event.  (Then, you can set it to whatever you want).  This value could be read from the satellite config and just applied to all riemann events generated by satellite-slave.  

This isn't currently supported and would require a small patch to satellite-slave.  It definitely seems like a good idea!  If you'd like to take a stab, we'd welcome a PR; otherwise, we'll discuss & work it into our roadmap.

Thanks again!

**Comment by ch3lo** [comment]
Hi @mforsyth,

Can you review the PR #56 

Regards
